# Generated by Django 4.1.6 on 2023-02-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='заголовок')),
                ('text', models.TextField(blank=True, db_index=True, verbose_name='текст')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='дата создания')),
                ('pub_date', models.DateTimeField(blank=True, null=True, verbose_name='дата публикации')),
                ('visible', models.BooleanField(default=False, verbose_name='видимый на сайте')),
                ('for_all', models.BooleanField(default=False, verbose_name='для всех – на странице «Заказы»')),
                ('for_registered', models.BooleanField(default=False, verbose_name='для всех зарегистрированных пользователей в ЛК')),
                ('for_contractors', models.BooleanField(default=False, verbose_name='для заказчиков в ЛК')),
                ('for_freelancers', models.BooleanField(default=False, verbose_name='для фрилансеров в ЛК')),
                ('for_new_freelancers', models.BooleanField(default=False, verbose_name='для новых фрилансеров в ЛК')),
                ('for_new_contractors', models.BooleanField(default=False, verbose_name='для новых заказчиков в ЛК')),
                ('for_core', models.BooleanField(default=False, verbose_name='для участников ядра в ЛК')),
            ],
            options={
                'verbose_name': 'новость',
                'verbose_name_plural': 'новости',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='NewsLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(db_index=True, max_length=255, verbose_name='текст ссылки')),
            ],
            options={
                'verbose_name': 'ссылка на статическую страницу',
                'verbose_name_plural': 'ссылки на статические страницы',
            },
        ),
    ]
