# Generated by Django 4.1.6 on 2023-02-26 14:15

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flatpages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='основной текстовый контент страницы')),
                ('text_block', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='дополнительный блок текста')),
                ('flatpage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='flatpages.flatpage')),
            ],
            options={
                'verbose_name': 'содержание страницы',
                'verbose_name_plural': 'содержание страницы',
            },
        ),
    ]
