# Generated by Django 4.1.6 on 2023-02-27 14:35

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_static_pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, db_index=True, max_length=55, verbose_name='заголовок')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='основной текстовый контент страницы')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_static_pages.staticpage', verbose_name='страница')),
            ],
        ),
    ]
