# Generated by Django 4.1.6 on 2023-02-27 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_static_pages', '0002_chapter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staticpage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='staticpage',
            name='text_block',
        ),
    ]
