# Generated by Django 4.1.6 on 2023-02-27 14:42

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_static_pages', '0003_remove_staticpage_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticpage',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='основной текстовый контент страницы'),
        ),
        migrations.AddField(
            model_name='staticpage',
            name='text_block',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='дополнительный блок текста'),
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
    ]
