# Generated by Django 4.1.6 on 2023-04-23 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=55, unique=True, verbose_name='Cчёт')),
            ],
            options={
                'verbose_name': 'счёт',
                'verbose_name_plural': 'счета',
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('RUB', 'Рубли'), ('USD', 'Доллары США')], default='RUB', max_length=3, verbose_name='валюта операции')),
                ('purpose_of_payment', models.CharField(max_length=255, verbose_name='назначение платежа')),
                ('summ', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='сумма')),
                ('time_operation', models.DateTimeField(auto_now_add=True, verbose_name='время проводки')),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='f_acc', to='app_accounts.account', verbose_name='счёт списания')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='t_acc', to='app_accounts.account', verbose_name='счёт зачисления')),
            ],
            options={
                'verbose_name': 'транзакция',
                'verbose_name_plural': 'транзакции',
                'ordering': ('-time_operation',),
            },
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='наименование фонда')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_accounts.account')),
            ],
            options={
                'verbose_name': 'фонд',
                'verbose_name_plural': 'фонды',
            },
        ),
    ]
