# Generated by Django 4.1.6 on 2023-04-06 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_category', '0002_activity_slug_categoryes_slug_specialization_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150)),
                ('description', models.TextField()),
                ('price', models.IntegerField(default=1000)),
                ('slug', models.SlugField(default='', max_length=100, unique=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_category.activity')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_category.categoryes')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_category.specialization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
