# Generated by Django 4.1.6 on 2023-04-22 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='customer',
        ),
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1', 'Предварительный'), ('2', 'Опубликованный'), ('3', 'Принятый'), ('4', 'Выполненный')], default='1', max_length=1, verbose_name='статус заказа'),
        ),
        migrations.CreateModel(
            name='OrderExecCust',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executor_status', models.CharField(choices=[('1', 'Кандидат'), ('2', 'Исполнитель')], max_length=1, verbose_name='статус исполнителя')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executors', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='app_orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(max_length=1000)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
