# Generated by Django 4.1.6 on 2023-02-26 14:15

import app_portfolio.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_ads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='заголовок')),
                ('description', models.TextField(verbose_name='описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio/covers/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg'], message='Ошибка загрузки: допускаются только файлы с расширением .jpg .png'), app_portfolio.validators.file_size_validate], verbose_name='обложка')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='дата создания')),
                ('corrected_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='дата изменения')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True, verbose_name='стоимость')),
                ('price_currency', models.CharField(blank=True, choices=[('USD', '$'), ('RUB', 'Р'), ('EUR', '€')], max_length=3, null=True, verbose_name='валюта')),
                ('time_spent', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='потрачено времени')),
                ('time_type', models.CharField(blank=True, choices=[('h', 'в часах'), ('d', 'в днях'), ('m', 'в месяцах')], max_length=3, null=True, verbose_name='время')),
                ('ordering', models.CharField(choices=[('1', 'Первая'), ('-1', 'Последняя'), ('0', 'По счёту')], db_index=True, default='0', max_length=3, verbose_name='сортировка')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='ссылка')),
                ('video', models.CharField(blank=True, max_length=255, null=True, verbose_name='видео')),
                ('file1', models.FileField(blank=True, null=True, upload_to='portfolio/files/%Y/%m/%d/', validators=[app_portfolio.validators.file_size_validate], verbose_name='файл1')),
                ('file2', models.FileField(blank=True, null=True, upload_to='portfolio/files/%Y/%m/%d/', validators=[app_portfolio.validators.file_size_validate], verbose_name='файл2')),
                ('file3', models.FileField(blank=True, null=True, upload_to='portfolio/files/%Y/%m/%d/', validators=[app_portfolio.validators.file_size_validate], verbose_name='файл3')),
                ('file4', models.FileField(blank=True, null=True, upload_to='portfolio/files/%Y/%m/%d/', validators=[app_portfolio.validators.file_size_validate], verbose_name='файл4')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='отображать на сайте')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='app_ads.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'работа',
                'verbose_name_plural': 'работы',
                'ordering': ['-created_at'],
            },
        ),
    ]
