# Generated by Django 4.1.6 on 2023-05-17 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0002_remove_fund_account_remove_operation_currency_and_more'),
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='acc',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='balance',
        ),
        migrations.AddField(
            model_name='customuser',
            name='rub_acc',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='rub_acc', to='app_accounts.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='usd_acc',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='usd_acc', to='app_accounts.account'),
            preserve_default=False,
        ),
    ]
