# Generated by Django 4.1.6 on 2023-05-17 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_remove_customuser_acc_remove_customuser_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='patronymic',
        ),
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default=None, max_length=255, unique=True, verbose_name='имя пользователя'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='slug',
            field=models.SlugField(max_length=55, unique=True),
        ),
    ]
