# Generated by Django 4.1.6 on 2023-04-23 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0003_customuser_acc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='username',
            new_name='slug',
        ),
    ]
