# Generated by Django 4.1.6 on 2023-04-18 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0004_customuser_specialty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='username',
            new_name='slug',
        ),
    ]
