# Generated by Django 4.1.6 on 2023-04-22 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_category', '0002_activity_slug_categoryes_slug_specialization_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecializationUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specializations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to='app_category.specialization')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
