# Generated by Django 4.1.6 on 2023-04-30 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_category', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialization',
            name='slug',
            field=models.SlugField(default='', max_length=155, unique=True),
        ),
    ]
