# Generated by Django 4.1.6 on 2023-04-23 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Get_referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('file1', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('file2', models.FileField(blank=True, upload_to='uploads/%Y/%m/%d/')),
                ('file3', models.FileField(blank=True, upload_to='uploads/%Y/%m/%d/')),
                ('file4', models.FileField(blank=True, upload_to='uploads/%Y/%m/%d/')),
                ('file5', models.FileField(blank=True, upload_to='uploads/%Y/%m/%d/')),
                ('choice_of_specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_category.specialization')),
            ],
            options={
                'verbose_name': 'запрос',
                'verbose_name_plural': 'запросы',
            },
        ),
    ]
