# Generated by Django 4.1.6 on 2023-04-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_referral_link', '0002_alter_get_referral_file1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='get_referral',
            name='file1',
            field=models.FileField(upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
